### ISSUE TITLE
`Null check operator used on a null value` when run retrofit

### ISSUE THREAD

**Issue by theoolee** [Carapacik/swagger_parser#110]
Failed to run retrofit_generator, [here](https://swaggerranslate-misc-awqpbcildi.cn-hangzhou.fcapp.run/?url=https://alliance-api-dev.zekehome.com/v2/api-docs) is the swagger.

**Comment by Carapacik** [comment]
@theoolee  for temp solution use retrofit_generator 7.0.8

**Comment by theoolee** [comment]
> @theoolee for temp solution use retrofit_generator 7.0.8

It works 👍🏻

**Comment by Carapacik** [comment]
@theoolee, you can upgrade the version to 8.0.2

**Comment by theoolee** [comment]
> @theoolee, you can upgrade the version to 8.0.2

Nice work.

**Comment by theoolee** [comment]
> Failed to run retrofit_generator, [here](https://swaggerranslate-misc-awqpbcildi.cn-hangzhou.fcapp.run/?url=https://alliance-api-dev.zekehome.com/v2/api-docs) is the swagger.

@Carapacik my swagger file still meets the same error.

**Comment by iiba-itabashi** [comment]
@Carapacik 
I faced the same error, too.
Occurs when there is only one "type: object" field in the request body.
The following is a concrete schema.
```
post:
  summary: Create a favorite_spot
  operationId: createFavoriteSpot
  tags:
    - favorite_spot
  security:
    - bearerAuth: []
  parameters:
    - in: path
      name: spot_id
      required: true
      schema:
        type: string
      description: ID of the spot
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            user: # Perhaps this is not handled well.
              type: string
              description: User ID
              example: "user123"

  responses:
    "201":
      description: FavoriteSpot created
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                $ref: "../schema/favorite_spot.yaml#/favorite_spot"
              status:
                type: string

```
