### ISSUE TITLE
Is there a way to cancel a request?

### ISSUE THREAD

**Issue by RyanRamchandar** [Carapacik/swagger_parser#112]
Since we are passing a Dio() client, is there a way to use a cancellation token for requests?

**Comment by RyanRamchandar** [comment]
Retrofit supports cancelling a request via the `@CancelRequest()` annotation, which uses Dio's cancellation feature. See: https://github.com/trevorwang/retrofit.dart/issues/85

**Comment by Carapacik** [comment]
Swagger does not have a designation in its scheme for cancel token and for some headerы, so it will not work that way. 
You'll have to add it manually.
