### ISSUE TITLE
Bug of model parser.

### ISSUE THREAD

**Issue by theoolee** [Carapacik/swagger_parser#114]
<img width="611" alt="image" src="https://github.com/Carapacik/swagger_parser/assets/45252670/1f5ea8c4-4888-4513-b998-6765868bd4bd">
<img width="591" alt="image" src="https://github.com/Carapacik/swagger_parser/assets/45252670/2d85217e-788c-4420-a6c6-ff423ed4a2e8">

Maybe is't not easy to be fixed.
But is there a way to access the raw value of the json? Otherwise there would be no way to get the response data.

**Comment by Carapacik** [comment]
Send a part of the diagram to make it easier to understand what the error is

**Comment by theoolee** [comment]
> Send a part of the diagram to make it easier to understand what the error is

swagger is [here](https://swaggerranslate-misc-awqpbcildi.cn-hangzhou.fcapp.run/?url=https://alliance-api-dev.zekehome.com/v2/api-docs), and you can find a model named `AppointmentCalendarPeriodDate`, which is generated to a class with single `additionalProperties`, properties defined in swagger were missing.

**Comment by theoolee** [comment]
The problem does not recur using the latest commit.

**Comment by theoolee** [comment]
In the `parseDataClasses` method of `swagger_parser/lib/src/parser/parser.dart`, the `AppointmentCalendarPeriodDate` model is added two times to the dataClasses, and one is with parameters, the other is without parameters.

**Comment by theoolee** [comment]
The side effect of `_findType` changes `_objectClasses` and all the classes in it are added to `dataClasses` at line 636, which causes the repetition.
