### ISSUE TITLE
errors when trying to generate the swagger reference Pet Store API

### ISSUE THREAD

**Issue by escamoteur** [Carapacik/swagger_parser#13]
Hi,

I'm currently evaluating different code generators from OpenAPI to Flutter. I tried yours too and I really like the resulting code, but there are two strange errors in the generated code:

![image](https://user-images.githubusercontent.com/16635729/217509448-5be83958-3f0f-40c1-93fa-ecf1408b9b13.png)

and 

![image](https://user-images.githubusercontent.com/16635729/217509522-2374221b-314d-495b-a955-27822b3bbb25.png)

under https://github.com/escamoteur/api_generators/tree/master/swagger_parser_test you can find the full project.

**Comment by Carapacik** [comment]
OK, thanks for the answer. I think it's a bug. I'll fix it during the day

**Comment by Carapacik** [comment]
Check with new version

**Comment by escamoteur** [comment]
fixed, thanks for the quick reaction, I know how it is to be a maintainer
