### ISSUE TITLE
How to handle Caching

### ISSUE THREAD

**Issue by appinteractive** [Carapacik/swagger_parser#162]
Hey, first, thanks for this awesome generator. 

I struggle a bit with how to use caching with it. All methods return Futures, but with caching they should return streams which first return the cached value and then the refreshed after that. So as far as I can tell, when using with the `DioCacheInterceptor` I will only get the cached value (depending on the setting and if it's cached already) but not the refreshed one. Is that correct or do I miss something?

Thanks in advance.

**Comment by Carapacik** [comment]
If this is not in the swagger definition, then it will not be generated.
