### ISSUE TITLE
multipart/form-data Files Type

### ISSUE THREAD

**Issue by simonmoser-bluesource** [Carapacik/swagger_parser#169]
In the current generated code the `dart:io File` type is used. This is also used in the [retrofit documentation](https://mings.in/retrofit.dart/file-_____w_retrofit.dart_retrofit.dart_retrofit_lib_http/Part-class.html).

I'm no expert in dart but a File is always a real File in the file system:
https://api.dart.dev/stable/3.3.0/dart-io/File-class.html

When i.e. I want to upload a file that is only available as byte array (i.e. an in memory image) to a server. I would have to save the byte array in a temp file and upload it.

A far simpler approach is to use `dio:Multipartfile`
https://pub.dev/documentation/dio/latest/dio/MultipartFile-class.html

A Multipartfile can also be loaded from a [path](https://pub.dev/documentation/dio/latest/dio/MultipartFile/fromFile.html). With this a File can easily converted to Multipartfile.

I manually changed the generated code to use `MultipartFile` instead of `File`, but this would maybe a welcome change by others, since it makes it far easier to handle file uploads.

The generated Code with MultipartFile:
```
@RestApi()
abstract class ClientClient {
  factory ClientClient(Dio dio, {String? baseUrl}) = _ClientClient;

  /// create  item
  @MultiPart()
  @POST('/api/item')
  Future<String> postApiItem({
    @Part(name: 'images') List<MultipartFile>? images,
  });
}

```

Example Yaml:
```
openapi: 3.0.2
info:
  title: API
  version: 1.0.0
paths:
  /api/item:
    post:
      summary: create  item
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: dummy
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Item:
      type: object
      properties:
        images:
          type: array
          items:
            description: Binary image
            format: binary
            type: string
```

**Comment by StarProxima** [comment]
Unfortunately, Retrofit does not support single MultipartFile
https://github.com/trevorwang/retrofit.dart/issues/529

**Comment by simonmoser-bluesource** [comment]
@StarProxima 
oh thanks for your answer! I used it with an array, which works. but was not aware that this is not possible with a single file with retrofit. 🙏

**Comment by JHMoneIQ** [comment]
How can we fix this? As it stands we can't write a file on web as far as I'm aware, so we have no way to create a file from say 
https://pub.dev/packages/cross_file

Which means that effectively there's no way to upload a file on an api on web?

**Comment by bluemon82** [comment]
@JHMoneIQ 
Sure just convert XFile to MultipartFile. If you use Retrofit oder swagger_parser you have to define an array of files, a single file does not work.

**Comment by JHMoneIQ** [comment]
... which means changing the API which can't be changed.

Seems like the only viable solution rightn ow is to manually create any endpoints that do this and ignore the one automatically created?

**Comment by bluemon82** [comment]
@JHMoneIQ 
I created a script which generates the code and afterwards patches the generated files, solved at least my problem back then:

```
#replace images to images[] and use MultipartFile instead of File
old_string="@Part(name: 'images') List<File>? images"
new_string="@Part(name: 'images[]') List<MultipartFile>? images"
sed -i '' -e "s/${old_string}/${new_string}/g" lib/api/marketplace/marketplace_client.dart
```
