### ISSUE TITLE
[dart] every attributes of a schema should be null

### ISSUE THREAD

**Issue by billyandco** [Carapacik/swagger_parser#21]
every attributes of a schema should be null with or without `required` key in schema
there's no way to set every attributes to null, even with a required key with empty array

**Comment by Carapacik** [comment]
I'm sorry, I didn't understand anything that was written...

**Comment by billyandco** [comment]
sorry

With the given structure
```
"Pair": {
  "type": "object",
  "properties": {
    "key": {
      "type": "string"
    },
    "value": {
      "type": "string"
    }
  }
},
```
it will generate 
```
import 'package:json_annotation/json_annotation.dart';

part 'pair.g.dart';

@JsonSerializable()
class Pair {
  const Pair({
    required this.key,
    required this.value,
  });

  factory Pair.fromJson(Map<String, dynamic> json) => _$PairFromJson(json);

  final String key;
  final String value;

  Map<String, dynamic> toJson() => _$PairToJson(this);
}
```

but i would like `key` and `value` attributes to be null

they would be not null only if i have this

```
"Pair": {
  "required": [
    "key",
    "value",
  ]
  "type": "object",
  "properties": {
    ...
  }
},
```

**Comment by Carapacik** [comment]
This is a moot point, because some languages don't do the required annotation, so you can't please everyone at once.
Therefore, it is better in some cases to correct with your hands.

**Comment by Carapacik** [comment]
There is also a `nullable` annotation, but they are also not supported by all languages.

**Comment by billyandco** [comment]
oh yeah i saw the nullable attributes, but what would be the default value of nullale if not present ?

this project can have different behavior depends on the language
would it be possible for `dart` to be :
- required or not nullable => required this.data
- not required and nullable => this.data?

**Comment by Carapacik** [comment]
Currently, it is required by default. If value have default parameter, required is false. `nullable` is not being processed yet, because there were few examples and few people use this annotation.

**Comment by fredx21** [comment]
I agree with @billyandco. It should be **not required and nullable => this.data**. In dart this makes a big difference in the constructor implementation requirement.
