### ISSUE TITLE
The object type in swagger should be converted into dynamic Map object

### ISSUE THREAD

**Issue by MsProfanum** [Carapacik/swagger_parser#214]
If the parameter in the swagger API has a type "object" it is converted by the parser into separate class instead of the dynamic `Map` or, ideally, `Map<String, NestedObject>` (with NestedObject being an object that is in the "$ref" of the "additionalProperties" json).

**Comment by StarProxima** [comment]
@MsProfanum Hi

Converting any object to a map is not a good idea, because it can be a list or a primitive. Map support with additionalProperties should work correctly. Can you check this with your examples?
