### ISSUE TITLE
Type generation

### ISSUE THREAD

**Issue by XanderD99** [Carapacik/swagger_parser#224]
### Steps to reproduce

create openapi spec with a path like
```yaml
  /nearby:
    get:
      summary: Get nearby places
      tags:
        - Generic
        - Locations
      responses:
        '200':
          description: Return everything nearby
          content:
            application/json:
              schema:
                type: object
                properties:
                  locations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Location'
```

run swagger parsert

### Expected results

typed reponse schema for the response with properties

```dart
@Freezed()
class GetNearbyResponse with _$GetNearbyResponse {
  const factory GetNearbyResponse({
    required List<Locations> locations,
  }) = _GetNearbyResponse;
  
  factory GetNearbyResponse.fromJson(Map<String, Object?> json) => _$GetNearbyResponseFromJson(json);
}
```

### Actual results

response class with no child parameteres

```dart
@Freezed()
class GetNearbyResponse with _$GetNearbyResponse {
  const factory GetNearbyResponse() = _GetNearbyResponse;
  
  factory GetNearbyResponse.fromJson(Map<String, Object?> json) => _$GetNearbyResponseFromJson(json);
}
```

### Your OpenApi snippet

  /nearby:
    get:
      summary: Get nearby places
      tags:
        - Generic
        - Locations
      responses:
        '200':
          description: Return everything nearby
          content:
            application/json:
              schema:
                type: object
                properties:
                  locations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Location'

### Dart version and used packages versions

<details><summary>Dart version</summary>

```console
Dart SDK version: 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "macos_arm64"```

</details><details><summary>Packages version</summary>

```console
^1.17.2
```

</details>

**Comment by StarProxima** [comment]
@XanderD99 Hi, this should be fixed in the latest version, can you test it with your examples?
