### ISSUE TITLE
includeIfNull for @JsonSerializable in the configuration

### ISSUE THREAD

**Issue by AntonShynkaretskyi** [Carapacik/swagger_parser#241]
### Use case

By default all the models are generated without `includeIfNull` value.

### Solutions considered

I haven't found any existing configuration for it.
Json also doesn't seems to be supporting any kind of global config for it.

### Proposal

It'd be awesome to be able to generate `@JsonSerializable(includeIfNull: false)` instead of `@JsonSerializable()` when necessary.

**Comment by Carapacik** [comment]
I don't see the point in this, because you can add includeIfNull globally immediately to build.yaml.
https://github.com/google/json_serializable.dart/tree/master/json_serializable#build-configuration
