### ISSUE TITLE
Feature: Root repository/interface

### ISSUE THREAD

**Issue by jascodes** [Carapacik/swagger_parser#28]
Hey @Carapacik 

Right now I m doing the follow

```
class RootRepo {
  final AuthRepo auth;
  const AppService({required this.auth});
}

final repositoryProvider = Provider<AppService>((ref) {
  final dio = ref.watch(dioProvider);
  return RootRepo(
    auth: AuthRepo(dio),
  );
});

```
I will have probably 20 repos like this as I migrate. And this is fine for most part. But it can be great if there is way to generate Root repo where are the other repo are initialised and automated as API changes.

What do you think?

**Comment by Carapacik** [comment]
I think this can be implemented, I also use the same interface to access different rest clients.
Maybe in version 1.0.0 we will do it.
