### ISSUE TITLE
Fix client_postfix option when not set

### ISSUE THREAD

**Issue by walsha2** [Carapacik/swagger_parser#31]
According to the documentation:

> Optional. Set postfix for client folder and Class. Works if there is only a single class or `squish_clients` is true. Default: ApiClient

However, when attempting to set an empty postfix in `swagger_parser.yaml`:

```dart
client_postfix: '' 
```

Results in an incorrect output (assume the client file name is `api_operations`):

```dart
part 'api_operations_.g.dart';
```

There is a trailing underscore when there should not be. Removing the underscore resolves the issue.

# Expected Result:

```dart
part 'api_operations.g.dart';
```

**Comment by Carapacik** [comment]
Thanks, I'll fix it sometime later
