### ISSUE TITLE
Default value for required fields

### ISSUE THREAD

**Issue by FerdiHr** [Carapacik/swagger_parser#50]
Hey thanks for the plugin it's really nice done ! 

I just have a problem with the default values 

```
@JsonSerializable()
class _$_Affiliateclick implements _Affiliateclick {
  const _$_Affiliateclick(
      {required this.book,
      required this.user,
      required this.partner,
      @JsonKey(name: 'deleted_at')
          required this.deletedAt,
      @JsonKey(name: 'created_at')
          required this.createdAt = '2023-05-21T19:09:37.812Z',
      @JsonKey(name: 'is_deleted')
          required this.isDeleted = false});
```

The two last are generated with a default value and still have a required prefix which raise an error. 
I think it's shouldn't have any required prefix.

**Comment by Carapacik** [comment]
At what input did you get this generation?
It is not reproduced on any similar ones.
