### ISSUE TITLE
Generated code does not work with JSON request format

### ISSUE THREAD

**Issue by mleevi** [Carapacik/swagger_parser#51]
I get the following error: `cannot be used to imply a default content-type, please set a proper content-type in the request`. Even though, in the openapi docs the request type is explicitly marked as application/json.

**Comment by Carapacik** [comment]
which version of dio are you using?

**Comment by Carapacik** [comment]
Mark content type:
```dart
Dio(
      BaseOptions(
        connectTimeout: const Duration(seconds: 30),
        receiveTimeout: const Duration(seconds: 300),
        contentType: Headers.jsonContentType, // like this 
      ),
    )
```

**Comment by mleevi** [comment]
Manually adding `.toJson` to the generated file fixes the problem

**Comment by Carapacik** [comment]
Nice

**Comment by mleevi** [comment]
> Mark content type:
> 
> ```dart
> Dio(
>       BaseOptions(
>         connectTimeout: const Duration(seconds: 30),
>         receiveTimeout: const Duration(seconds: 300),
>         contentType: Headers.jsonContentType, // like this 
>       ),
>     )
> ```
 
This does not work if some endpoints expect `application/x-www-form-urlencoded` response
