### ISSUE TITLE
How to make a list of nullable items?

### ISSUE THREAD

**Issue by mleevi** [Carapacik/swagger_parser#68]
I want to return an array of a type, that can also contain null values. But even if I set `"nullable": true` in the items the generated list always contains non-null type.

E.g. In the example Pets api if I change findPets response from:

```
 "items": {
    "$ref": "#/components/schemas/Pet"
 }
```

to:
```
"items": {
    "nullable": true,
    "$ref": "#/components/schemas/Pet"
}
```

Even then the resulting code is the same `List<Pet>` instead of `List<Pet?>`

**Comment by Carapacik** [comment]
Thanks
