### ISSUE TITLE
[Bug]: Created enums are not renamed according to replacementRules

### ISSUE THREAD

**Issue by n-gras** [Carapacik/swagger_parser#69]
Hi!

First off, great tool! Has saved me many hours of work, so thank you!

I have run into a bug, when renaming Enums through swagger_parser.yaml. The classes that use the enums, are referring to the renamed file, however, the Enums themselves don't get renamed. It seems to be an oversight in parser.dart, specifically, I've added, to line472:  key = replacementRule.apply(key)!;
This fixes the issue for me.

Thanks and have a great day!

**Comment by Carapacik** [comment]
Thanks for this issue
