### ISSUE TITLE
Flag to use the path for the generated method name

### ISSUE THREAD

**Issue by StarProxima** [Carapacik/swagger_parser#87]
This feature request is related to https://github.com/Carapacik/swagger_parser/issues/83.

**Proposal**

Add a flag to the swagger_parser configuration that leaves only path in the method name.

```yaml
swagger_parser:
  path_for_method_name: false # Optional. Set to 'true' to use only the endpoint path for the method name. If set to false, the operationId will be used. Default: false
```

**Motivation**

Sometimes the summary in OpenAPI can be irrelevant (invalid, too long or short, in a different language), which can be confusing when searching for the right method in the api client. 

The optional flag will leave only path in the name, which will allow better navigation through the code.

**Suggested behavior**

Current method generation:
```dart
  @POST('/auth/email/verify')
  Future<void> emailUsersDbAuthEmailVerifyPost({
    @Body() required Object body,
  });
```
Proposed method generation:
```dart
  @POST('/auth/email/verify')
  Future<void> authEmailVerifyPost({
    @Body() required Object body,
  });
```
OpenAPI:
```json
{
  "openapi": "3.1.0",
  "info": {
    "title": "Microservice Auth API methods",
    "version": "0.2.2"
  },
  "paths": {
    "/auth/email/verify": {
      "post": {
        "tags": [
          "Email"
        ],
        "summary": "Проверить Email на cуществование в users_db",
        "description": "Вернет True, если пользователь с указанным Email уже зарегистрирован, иначе False.",
        "operationId": "Проверить_Email_на_существование_в_users_db_auth_email_verify_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "type": "object"
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by Carapacik** [comment]
I think you can do something similar
`optional_id_for_method_name` As you have only the opposite.

**Comment by Carapacik** [comment]
Something like this code

https://github.com/Carapacik/swagger_parser/blob/2c3a7dfa57cc41ccf6181400ad5c51e6f188e01c/swagger_parser/lib/src/parser/parser.dart#L406
```dart
if (thisBoolVariable) {
  requestName = (key + path).toCamel
}
```

**Comment by StarProxima** [comment]
Okay, got it. I'll try to implement e this week.

What's the final name and description (docs) for the flag?

**Comment by Carapacik** [comment]
path_method_name : false
